### ISSUE TITLE
[Bug]: Wrong default public API URL

### ISSUE THREAD

**Issue by naXa777** [danielschuster-muc/potter-db#177]
### Project

Website (Potter DB Search)

### Bug description

Front-end is using https://potter-db-herokuapp.com/status to check API status.

### Expected Behavior

Front-end is using https://potter-db-api.herokuapp.com/status to check API status.

### Steps to reproduce

Just follow the steps in the frontend/README.md file.
When you visit http://localhost:3001 in browser, you'll see the 503 error.

### Screenshots

![image](https://user-images.githubusercontent.com/3858548/193472459-7703a263-3f84-4c69-bb2c-255f817e087c.png)

**Comment by naXa777** [comment]
I'm going to fix this bug myself. It's a quick one.

**Comment by danielschuster-muc** [comment]
Thank you for opening this bug. That's something I totally oversaw as I almost always used the env variable 😂.
