### ISSUE TITLE
[Issue]: Voldemort Character Card

### ISSUE THREAD

**Issue by chinmayayy** [danielschuster-muc/potter-db#192]
### Project

Website (Potter DB Search)

### Describe the feature you want to request

I realized that the DB currently has the main villain itself missing :) 
`https://potterdb.com/characters?q=voldemort` 
I could work on collecting the Wiki and contribute, thanks!

**Comment by danielschuster-muc** [comment]
Thank you for submit this issue. 
Voldemort is already in the DB: https://potterdb.com/characters/tom-riddle
The Search itself currently only searches by the original name of the character and not on alias names such as "Lord Voldemort".

**Comment by chinmayayy** [comment]
I understand but I think it just makes more sense for anyone looking up info since the alias is much more popular in this context. Thanks, anyway!

**Comment by danielschuster-muc** [comment]
Yes, searching by alias would be definitely better. I will probably create a issue / idea for it, if anyone wants to implement it.

**Comment by chinmayayy** [comment]
Great! Would you want to implement this as a separate entity in the database or some other way around?

**Comment by danielschuster-muc** [comment]
I currently working on it.
