### ISSUE TITLE
[Feature Request]: Better summaries for movies

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#201]
### Project

API

### Describe the feature you want to request

Currently the summaries of the movies in the API are very boring and lacking of content. 

### (Optional) Describe a solution for this feature

Write new, better and more meaningful summaries for each movie. The files for the movies can be found [here](https://github.com/danielschuster-muc/potter-db/tree/master/backend/db/data/movies).
Make sure to write own and not copied summaries, as I won't accept summaries copied from somewhere else.

**Comment by umeshchavda05** [comment]
hey can i work on this under hacktoberfest?

**Comment by danielschuster-muc** [comment]
Sure, all contributions should automatically take part in hacktoberfest, as this repository has the hacktoberfest label.
