### ISSUE TITLE
[Feature Request]: 404 Page

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#202]
### Discussed in https://github.com/danielschuster-muc/potter-db/discussions/172

<sup>Originally posted by **danielschuster-muc** October  1, 2022</sup>

# Project

Website (Potter DB Search)

# Describe the feature you want to request

When you get to a page that is not found, you will see a very empty 404 page. 

# (Optional) Describe a solution for this feature
Edit the [404 page](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/src/pages/404.js) inspired by the image below.

The title of the page should be `Have you seen this page?`.
In the middle the image with Sirius and below a paragraph with `Approach with extreme caution! To not attempt to use magic against this site!`
There should also be a button to go back to the homepage. 

Make sure to follow the style of other page, use [MUI](https://mui.com/material-ui/getting-started/overview/) and proper credit the image of Sirius in the [Attribution file](https://github.com/danielschuster-muc/potter-db/blob/master/ATTRIBUTION.md).

![image](https://user-images.githubusercontent.com/90754725/194039761-45ed2b6c-aa69-4070-b1df-6ca2ef90cb48.png)

**Comment by PeritusDeveloper** [comment]
I want to do this

**Comment by kirtanchandak** [comment]
Hey, can I take this issue ?

**Comment by danielschuster-muc** [comment]
@PeritusDeveloper on which issue are you currently working? #202 or #204? 
Maybe @kirtanchandak can work on one of those, as you are currently assigned to two issues?

**Comment by kirtanchandak** [comment]
@danielschuster-muc are these Hacktoberfest issue ? as you have removed the Hacktoberfest tag from it

**Comment by danielschuster-muc** [comment]
> @danielschuster-muc are these Hacktoberfest issue ? as you have removed the Hacktoberfest tag from it

All issues / PRs count automatically for hacktoberfest, as this repository is labeled with `hacktoberfest`.
But please wait for @PeritusDeveloper's reply before working on this feature request.

**Comment by PeritusDeveloper** [comment]
I am about to finish both
I will submit both by **evening tomorrow**
If I dont you can assign any one to other person

**Comment by danielschuster-muc** [comment]
Sure, no problem. It can also take a bit longer if you need the time. It's just important for me to know whether people are still working on their features, so I can organise it better.

**Comment by kirtanchandak** [comment]
as @PeritusDeveloper is working this issue, can you assign me the other one

**Comment by danielschuster-muc** [comment]
> I will submit both by evening tomorrow
That sounds for like he is working on both.

**Comment by PeritusDeveloper** [comment]
@danielschuster-muc you can assign him this issue
it's fine for me
I will do the navbar one

**Comment by danielschuster-muc** [comment]
You still working on it @kirtanchandak? Or should I unassign you?
