### ISSUE TITLE
[Feature Request]: 500 Error Page

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#203]
### Discussed in https://github.com/danielschuster-muc/potter-db/discussions/172

<sup>Originally posted by **danielschuster-muc** October  1, 2022</sup>
# Project

Website (Potter DB Search)

# Describe the feature you want to request

Similar to the current 404 page (see #202), the [500 error page](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/src/pages/500.js) (when an internal server error occurs) is also very empty at the moment. 

# (Optional) Describe a solution for this feature

Edit the [500 error page](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/src/pages/500.js) and include an image of Harry and Ron crashing in the The Whomping Willow. 

As the title of the page write `500 - Internal Server Error` and the subtitle `Hm, looks like the server crashed. Please try again later or contact us by write a GitHub Issue if the problem persists.`
There should also be a button / link to this [Issue Tracker](https://github.com/danielschuster-muc/potter-db/issues/new/choose).

Make sure to follow the style of other page, use [MUI](https://mui.com/material-ui/getting-started/overview/) and proper credit the image of the Whomping Willow you used in the [Attribution file](https://github.com/danielschuster-muc/potter-db/blob/master/ATTRIBUTION.md).

**Comment by Mitternachtsmond** [comment]
I would like to do this

**Comment by kirtanchandak** [comment]
hey are you working on this ? please assign this issue to me if not..

**Comment by Mitternachtsmond** [comment]
I am working on it @kirtanchandak

**Comment by Mitternachtsmond** [comment]
I am stuck

**Comment by danielschuster-muc** [comment]
With what exactly do you need help?

**Comment by var-rishabh** [comment]
@danielschuster-muc 
Can I work on this issue. I can create a error 500 page with some unique design. I have something in my mind.

**Comment by danielschuster-muc** [comment]
I guess @Mitternachtsmond is still working on it..,

**Comment by var-rishabh** [comment]
Please let me know if you want to assign ii to someone else.

**Comment by danielschuster-muc** [comment]
Sure, I will, if @Mitternachtsmond isn't working on it anymore.

**Comment by var-rishabh** [comment]
okay! cool
