### ISSUE TITLE
[Feature Request]: Improved Navbar

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#204]
### Discussed in https://github.com/danielschuster-muc/potter-db/discussions/182

<sup>Originally posted by **ahmedsilat44** October  3, 2022</sup>

# Project

Website (Potter DB Search)

# Describe the feature you want to request

So while using the website. I think it would improve the experience if there was a navbar.

# (Optional) Describe a solution for this feature

Add a hamburger menu which opens a dropdown where you can see also the information from the footer, e.g. General, Search and Information and their sub links. 

Make sure to follow the style of the other pages on the Website and use [MUI](https://mui.com/material-ui/getting-started/overview/).

![image](https://user-images.githubusercontent.com/105588821/193515257-988e6f23-729d-42a6-bc1a-4dc22ad73273.png)

**Comment by PeritusDeveloper** [comment]
Please assign it to me

**Comment by kirtanchandak** [comment]
If no one's working I am ready to take this issue

**Comment by PeritusDeveloper** [comment]
@kirtanchandak You can take this if you need to complete your required PR's
