### ISSUE TITLE
[Bug]: footer~ sitemap link is broken

### ISSUE THREAD

**Issue by Nakamcode** [danielschuster-muc/potter-db#207]
### Project

Website (Potter DB Search)

### Bug description

The sitemap link is broken under the footer

### Expected Behavior

When click it should take me to the sitemap page

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by taramatt93** [comment]
I can pick this up! Any chance of this counting towards Hacktoberfest?

**Comment by Nakamcode** [comment]
Alright sure, you can work on it. All the best

**Comment by danielschuster-muc** [comment]
What do you mean by the Sitemap link is broken? It works on the potterdb.com website.
If it’s not working in development, that’s normal, you first need to build the the project by running `npm run build` as the Sitemap is created when you build it.

**Comment by taramatt93** [comment]
@danielschuster-muc You're absolutely right, I just jumped at the chance to contribute to this project!

**Comment by shivam-sharma7** [comment]
@Nakamcode can you provide me site link which you want to map.

**Comment by danielschuster-muc** [comment]
So I can close the issue now?

**Comment by Nakamcode** [comment]
### Here's what I'm referring to when the sitemap link is clicked!
![captures_chrome-capture-2022-9-6](https://user-images.githubusercontent.com/89482825/194388336-cf2fc4e9-850d-40db-a075-a4c7877fa31b.png)

**Comment by danielschuster-muc** [comment]
Just go to `/sitemap-0.xml` as the sitemap is indexed.

**Comment by Nakamcode** [comment]
Alright
