### ISSUE TITLE
[Feature Request]: Create Potion Pages

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#209]
### Project

Website (Potter DB Search)

### Describe the feature you want to request

The [API](https://api.potterdb.com/v1/potions) also gives data for Potions from the Harry Potter Universe. 
Therefore there should be pages for potions on the website, too. 

### (Optional) Describe a solution for this feature

Create a page to list all potions (similar to the [character list](https://github.com/danielschuster-muc/potter-db/tree/master/frontend/src/pages/characters/index.js)) and a general slug-based page for detailed information about a specific potions (such as [here](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/src/pages/characters/%5Bslug%5D/index.js)).
For the fetching of the data make sure to also create a new load_potions.js file similar to this [one](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/src/lib/load_characters.js). 

You also should link the potions page in the [footer](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/src/components/layout/Footer.js#L31).

Make sure to have the same folder structure and layout as the other pages (characters and movies).

If you have any questions, feel free to leave a comment below.

**Comment by eduardconstantin** [comment]
Hello! Could you assign this to me?
