### ISSUE TITLE
[Feature Request]: Create Spells Pages

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#210]
### Project

Website (Potter DB Search)

### Describe the feature you want to request

The [API](https://api.potterdb.com/v1/spells) also gives data for Spells from the Harry Potter Universe. 
Therefore there should be pages for spells on the website, too. 

### (Optional) Describe a solution for this feature

Create a page to list all spells (similar to the [character list](https://github.com/danielschuster-muc/potter-db/tree/master/frontend/src/pages/characters/index.js)) and a general slug-based page for detailed information about a specific spells (such as [here](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/src/pages/characters/%5Bslug%5D/index.js)).
For the fetching of the data make sure to also create a new load_spells.js file similar to this [one](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/src/lib/load_characters.js). 

You also should link the spells page in the [footer](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/src/components/layout/Footer.js#L31).

Make sure to have the same folder structure and layout as the other pages (characters and movies).

If you have any questions, feel free to leave a comment below.

**Comment by druwan** [comment]
I could give this a go

**Comment by danielschuster-muc** [comment]
Sure, I will assign it to you!

**Comment by druwan** [comment]
I get an error in `src/components/pages/spells/[slug]/SpellDetails.js` while trying to fill the `AccordionList`

Following the examples from both movie and character, I assumed that I could do 

```js
const { name, effect, ... } = attributes

const accordions = [
{
  name: 'effect',
  value: effect,
},...
```

However I do end up with an error at `src/components/ui/CustomAccordion.js (36:19) @ CustomAccordion`with message "TypeError: array.map is not a functionTypeError: array.map is not a function"

I'm pretty sure I'm providing an array?

**Comment by danielschuster-muc** [comment]
You can’t use `effect‘ as we need an array for the accordions. The only thing you could do would be converting it to an array (e.g. by surrounding it with square brackets). But you probably don’t need those accordions at all, as there are no array values in the spells.
