### ISSUE TITLE
[Feature Request]: Implement ESLint and Prettier & 

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#215]
### Project

Website (Potter DB Search)

### Describe the feature you want to request

Everyone has different code styles, therefore it would be useful to implement prettier and eslint to have a general code style for Potter DB. 

### (Optional) Describe a solution for this feature

Install prettier and eslint, configure it for next.js and for compatibility between those. 
Options should be default, see [here](https://prettier.io/docs/en/options.html). 
Additionally add a git hook to automatically format and lint the files on commiting.

**Comment by Kit-p** [comment]
Is it okay for me to work on this?
I plan to use [husky](https://github.com/typicode/husky) to manage the pre-commit git hook.

**Comment by danielschuster-muc** [comment]
Sure, I will assign you. 
Husky sounds like a good tool to implement the hook 👍.
