### ISSUE TITLE
[Feature Request]: Create new placeholder svg images

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#216]
### Project

Website (Potter DB Search)

### Describe the feature you want to request

As there are more pages movies, spells and potions planned (see #210 and #209), we need more placeholder images for missing images. 

### (Optional) Describe a solution for this feature

Create your own (not copied) images for: 
- characters
- movies
- spells
- potions
- books

Those images should be in a **svg format**, **simple** and silhouette of the respective topic, e.g. for characters a silhoutte of a (person with a wizard hat or something similar.
**Don't just copy images from anywhere else, as I don't want any sort of copyright infringement and I therefore won't accept any PRs of that kind.**

**Comment by eduardconstantin** [comment]
Assign me, please!

**Comment by eduardconstantin** [comment]
I made a PR [here](https://github.com/danielschuster-muc/potter-db/pull/220), could you take a look and tell me if it's ok the sample that I did so I can continue with the other placeholders

**Comment by danielschuster-muc** [comment]
The first image looks really good!
