### ISSUE TITLE
[Feature Request]: Create Sitemap for API

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#221]
### Project

API

### Describe the feature you want to request

For SEO it's important to create a sitemap to inform the search engines about available sites. 
Therefore a sitemap is essential for the api. 

### (Optional) Describe a solution for this feature

Use the [sitemap_generator](https://rubygems.org/gems/sitemap_generator) gem to generate the sitemap. 

For the `default_host` use `https://api.potterdb.com`.  
Please create the sitemaps only for the collections, e.g.` /v1/characters` and not for every `/v1/characters/:slug`. 

You should also link the sitemap in `robots.txt`.

**Comment by techrajdeep** [comment]
I am looking for an issue for my first contribution . Can you help me here. Can I take on this .

**Comment by danielschuster-muc** [comment]
Do you have any prior ruby/ rails experience? Else it can be very hard to work on this issue.

**Comment by danielschuster-muc** [comment]
But of course you can try it and I will give you some tips if you need any help @techrajdeep.

**Comment by techrajdeep** [comment]
Sure..I will try..Need your guidance..

**Comment by danielschuster-muc** [comment]
For what exactly do you need help with?
