### ISSUE TITLE
[Feature Request]: Create Book Pages

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#225]
### Project

Website (Potter DB Search)

### Describe the feature you want to request

The API also provides data for [Books](https://api.potterdb.com/v1/books) and [Chapters](https://api.potterdb.com/v1/books/harry-potter-and-the-philosopher-s-stone/chapters) from the Harry Potter Universe.
Therefore there we should add pages for books, too. 

### (Optional) Describe a solution for this feature

Create a page to list all books (similar to the [movie list](https://github.com/danielschuster-muc/potter-db/tree/master/frontend/src/pages/movies/index.js)) and a general slug-based page for detailed information about a specific book (such as [here](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/src/pages/book/%5Bslug%5D/index.js)).

For the fetching of the data make sure to also create a new load_books.js file similar to this [one](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/src/lib/load_movies.js), this should also fetch individual chapters of each book.

The AccordionList in the [DetailsPage](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/src/components/pages/movies/%5Bslug%5D/MovieDetails.js#L104) should contain the different chapters (e.g. name as and summary as the array content). 

You also should link the books page in the [footer](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/src/components/layout/Footer.js#L31).

Make sure to have the same layout and folder structure like other pages (characters, movies, spells, potions).

If you have any questions, feel free to leave a comment below.

**Comment by chintan0513** [comment]
In which language do you want to make Book pages? Is it React.js or Next.js?

**Comment by danielschuster-muc** [comment]
It‘s Next.js and MUI, just look how I did it with the other pages.

**Comment by eduardconstantin** [comment]
If no one is taking this issue I can do it.

**Comment by chintan0513** [comment]
Yes you can do it :)

**Comment by eduardconstantin** [comment]
@chintan0513 is not hard to do the pages, you have the other pages that you can copy from.

**Comment by danielschuster-muc** [comment]
If @chintan0513 is ok with it, you can work on it @eduardconstatin.

**Comment by eduardconstantin** [comment]
> If @chintan0513 is ok with it, you can work on it @eduardconstatin. 

Ok

**Comment by eduardconstantin** [comment]
Seems it's mine after all

**Comment by danielschuster-muc** [comment]
Yep, I guess, that's why I assigned it to you.
