### ISSUE TITLE
[Bug]: Responsive issue of inputs in home screen.

### ISSUE THREAD

**Issue by ST1LLWATER** [danielschuster-muc/potter-db#227]
### Project

Website (Potter DB Search)

### Bug description

The inputs align in a single line on mobile devices affecting UX.
![image](https://user-images.githubusercontent.com/62516824/194767215-c8cb17a4-a4c5-40b9-8d58-0079832be8d6.png)

### Expected Behavior

Inputs to be aligned below each other for improved visibility, and better handling of by the user.

### Steps to reproduce

Open homepage in mobile device.

**Comment by ST1LLWATER** [comment]
Allow me to work on this, thanks.

**Comment by danielschuster-muc** [comment]
Yep, that's definitely something that should be fixed. I assigned it to you.
