### ISSUE TITLE
[Feature Request]: New Logo

### ISSUE THREAD

**Issue by umeshchavda05** [danielschuster-muc/potter-db#231]
### Project

Website (Potter DB Search)

### Describe the feature you want to request

The current logo is very simple and I think it can be improved upon.

### (Optional) Describe a solution for this feature

I can make a new and unique logo using Canva.

**Comment by umeshchavda05** [comment]
@danielschuster-muc can i work on this as a no-code contribution to hacktoberfest?

**Comment by danielschuster-muc** [comment]
The current logo should definitely get an overall improvement. Sure, you can work on it and I will assign you. 

About the design of the logo:
- should be a svg icon (and therefore scalable for usage as the favicons etc.)
- should use the color #d500f9 
- should contain a bolt
- should not be to complex

**Comment by danielschuster-muc** [comment]
So I was thinking of the logo again. Especially the icon itself, e.g. used for the favicon looks very thin. Maybe you have any idea how to make it better visible? 

![favicon bolt](https://user-images.githubusercontent.com/90754725/196046396-8c26a854-fb59-4c72-8d27-cbb9612ee86f.JPG)



And about the logo: 
![image](https://user-images.githubusercontent.com/90754725/196046372-899e5faf-b32a-41c9-a775-5994a6a4f600.png)
Maybe you can move the bolt nearer to the font itself?

**Comment by danielschuster-muc** [comment]
@umeshchavda05 do you think you can do those improvements? Would be awesome!
