### ISSUE TITLE
[Feature Request]: Adding docker build and docker-compose for faster and reproducible local builds

### ISSUE THREAD

**Issue by aliabbasjaffri** [danielschuster-muc/potter-db#293]
### Project

Other (Please specify in the description)

### Describe the feature you want to request

I would like to add docker to the project to have a single client, clean setup of the application locally. This could also be used to deploy those containers in production; if needed.

**Comment by danielschuster-muc** [comment]
I don’t see why we would need that and for which part exactly. The backend (ruby on rails) is hosted on Heroku, no need for Docker for production. The Frontend / Docs (next.js / node) are hosted on vercel and don’t need docker, neither.
Or what exactly do you mean by 'Adding Docker'?
