### ISSUE TITLE
[Bug]: Filtering / Searching doesn't work

### ISSUE THREAD

**Issue by Weranika** [danielschuster-muc/potter-db#585]
### Project

Website (Potter DB Search)

### Bug description

filter and sorting return 500 error, when i try get reques like https://api.potterdb.com/v1/characters?sort=-name or [https://api.potterdb.com/v1/characters?filter[name_cont_any]=har](https://api.potterdb.com/v1/characters?filter%5Bname_cont_any%5D=har)

### Screenshots

```bash
![error](https://i.imgur.com/6drXFhV.png)
```

**Comment by danielschuster-muc** [comment]
Thanks for opening this issue! I could reproduce it in production and dev - seems to be an issue with ransack (the gem I use for filtering). 
You can probably expect a fix for it soon.
