### ISSUE TITLE
[Bug]: Improving UI

### ISSUE THREAD

**Issue by dfordp** [danielschuster-muc/potter-db#743]
### Project

Website (potterdb.com)

### Bug description

I can help make the front end more attractive allowing new users to be able to learn more about api

### Expected Behavior

- Mobile Optimization
- Better UI/UX and fonts

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by danielschuster-muc** [comment]
Hi there, thank you for your interest in contributing. 
As I am currently working on revamping the website (see new-website branch, still in very early stage) I am not quite sure how I should move on with your idea / issue. 
Could you maybe give me some more details on what you are planning to do?

**Comment by dfordp** [comment]
Changes I would Make:
- Inclusion of Tailwind CSS
- Adding ShadCN Components
- Changing the Font in the website
- Placing and aligning Components to give a modern UI Look to the website. 

You can refer to my projects in my profile to see my work

**Comment by danielschuster-muc** [comment]
I don't think it makes that much sense to make so many changes to the frontend as I am currently rebuilding the whole website code.
