### ISSUE TITLE
[Feature Request]:  Add a customized scroll-bar in the website

### ISSUE THREAD

**Issue by Arbtrage** [danielschuster-muc/potter-db#748]
### Project

Website (potterdb.com)

### Describe the feature you want to request

There could be a customized scroll bar for the website to make it look more amazing .

### (Optional) Describe a solution for this feature

With out scrollbar it looks this this
<img width="860" alt="image" src="https://github.com/danielschuster-muc/potter-db/assets/100552235/a55dedd1-3756-40f2-9793-3f453fe5a93d">

If a custom scroll bar is added , it would look more magical
<img width="845" alt="image" src="https://github.com/danielschuster-muc/potter-db/assets/100552235/17a43264-edaf-48d8-83fd-9e4592d09dba">

### (Optional) Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Arbtrage** [comment]
@danielschuster-muc , I would like to work on this issue. Please assign me this.

**Comment by danielschuster-muc** [comment]
Hi there, yes this sounds like a good addition for the Potter DB Website. 
Please be aware that we don’t accept pull requests to the old website. Make sure to branch off from `new-website` (https://beta.potterdb.com).
See the [contribution section](https://github.com/danielschuster-muc/potter-db/tree/master/frontend#contributing) in the frontend readme.

**Comment by Arbtrage** [comment]
Sure, I will create a PR for the `new-website` branch .

**Comment by Arbtrage** [comment]
Hi @danielschuster-muc , I have made a PR for this issue. Please review and if some changes are needed I would be happy to do them .

**Comment by danielschuster-muc** [comment]
closed with #749
