### ISSUE TITLE
[Ticket]: Add Potions Pages

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#764]
### Project

Website (potterdb.com)

### Describe the ticket you want to create

In building the [new website](https://beta.potterdb.com/) (see `new-website` branch) we need your help. 
This ticket is about creating the potions `index` (list/overview) and `show` (details) pages. 

### Get started
- Please add a short note below before starting with this ticket, so I can assign it to you. 
- Fork this repo and make sure to branch up from `new-website`. 
- Start implementing the features (see Acceptance Criteria). 

You can get some inspiration by looking at the old [potions page](https://potterdb.com/potions). But make sure to keep it in a similar style as the new character pages.

If you have any questions or concerns, feel free to ask below. 

### Acceptance Criteria

- [ ] Add the potion index and show page.
- [ ] Create skeleton animations that fit with the actual content.
- [ ] Make sure to split the content in useful components.
- [ ] Add metadata for SEO.
- [ ] Add `/potions` link in Footer.

### Additional Details

https://github.com/danielschuster-muc/potter-db/tree/new-website/frontend/src/components/characters
https://github.com/danielschuster-muc/potter-db/tree/new-website/frontend/src/app/characters
https://beta.potterdb.com/characters

**Comment by westerandr** [comment]
Hi there! I would love to work on this ticket please :)

**Comment by danielschuster-muc** [comment]
> Hi there! I would love to work on this ticket please :)

sure, there you go
