### ISSUE TITLE
[Ticket]: Add Spells Pages

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#765]
### Project

Website (potterdb.com)

### Describe the ticket you want to create

In building the [new website](https://beta.potterdb.com/) (see `new-website` branch) we need your help. 
This ticket is about creating the spells `index` (list/overview) and `show` (details) pages. 

### Get started
- Please add a short note below before starting with this ticket, so I can assign it to you. 
- Fork this repo and make sure to branch up from `new-website`. 
- Start implementing the features (see Acceptance Criteria). 

You can get some inspiration by looking at the old [spells page](https://potterdb.com/spells). But make sure to keep it in a similar style as the new character pages.

If you have any questions or concerns, feel free to ask below. 

### Acceptance Criteria

- [ ] Add a spell index and show page.
- [ ] Create skeleton animations that fit with the actual content.
- [ ] Make sure to split the content in useful components.
- [ ] Add metadata for SEO.
- [ ] Add `/spells` link in Footer.

### Additional Details

https://github.com/danielschuster-muc/potter-db/tree/new-website/frontend/src/components/characters
https://github.com/danielschuster-muc/potter-db/tree/new-website/frontend/src/app/characters
https://beta.potterdb.com/characters

**Comment by sushma1031** [comment]
Hello, I'm interested in working on this. Before I start, I want to clarify whether I should create the required types for the spells? If yes, what are the attributes I should include?

**Comment by danielschuster-muc** [comment]
Yes, exactly you should also create the spell types. I think the [docs](https://docs.potterdb.com/resources/spells) should be sufficient for reference, or have a look at the [api responses](https://api.potterdb.com/v1/potions). Thanks for your interest in contributing.

**Comment by sushma1031** [comment]
All right, thanks! Could you please assign the issue to me?

**Comment by sushma1031** [comment]
Can I reuse the `CharacterListSkeleton` component for the spell index page skeleton? If yes, can I move that file to a common folder outside the `characters/` folder within the `components/` folder?

**Comment by danielschuster-muc** [comment]
Yes, you're right, makes sense to reuse it for other pages like the spells. Sure.
