### ISSUE TITLE
[Feature Request]: Styling the cards

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [danielschuster-muc/potter-db#781]
### Project

Website (potterdb.com)

### Describe the feature you want to request

- Related to frontend.
- Font style and font size according to the style of the card.
- Font color related to the card color.
- Image fixed relative to the dimension of the card.
- Moving and glowing card effect.

### (Optional) Describe a solution for this feature

![image](https://github.com/danielschuster-muc/potter-db/assets/114330097/84a6fd51-65f8-44ca-9a89-08ee9fe55070)

- Not a good User interface of the cards.

### (Optional) Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Avdhesh-Varshney** [comment]
@danielschuster-muc please assign this task to me to contribute under hacktoberfest 2023

**Comment by danielschuster-muc** [comment]
As there's currently a rewrite of the Potter DB website, see https://beta.potterdb.com/ and the `new-website` branch, it doesn't make sense to do changes to the old website.
