### ISSUE TITLE
[Ticket]: Create a ScrollToTop button

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#787]
### Project

Website (potterdb.com)

### Describe the ticket you want to create

For the new website it would be nice to have a scroll to top button such as we had on the [old website](https://potterdb.com/characters). 

It should be positioned in the bottom right of the page and only be visible when needed (e.g. unless you are a the top of the page).
When clicked it should smoothly move the page to the top. 
For the icon make sure to use [react-icons](https://react-icons.github.io/react-icons/). Do not use any other packages.

Please be aware to make a branch from the `new-website` branch. 
Before start working on this ticket please **leave a quick note below** so I can assign you. If you have any questions please ping me.

### Acceptance Criteria

- [ ] Add a ScrollToTop button that smoothly moves to the top of the page.
- [ ] It fits with our color theme (see [tailwind.config.ts](https://github.com/danielschuster-muc/potter-db/blob/new-website/frontend/tailwind.config.ts)).
- [ ] It's only visible when needed. 
- [ ] Works also for mobile usage.

**Comment by kristenking** [comment]
Hello @danielschuster-muc ! Could I work on this issue please?

**Comment by vyb2014962** [comment]
hi @danielschuster-muc ! can i take this?

**Comment by danielschuster-muc** [comment]
> hi @danielschuster-muc ! can i take this?

sorry, @kristenking was first 😂 , but I will add some more tickets soon and if you have any ideas, feel free to open an feature request or discussion.

**Comment by kristenking** [comment]
Hey @danielschuster-muc , I just checked, and looks like the scroll-up button already exists on the newer version. Could you please confirm with me if there is anything else I can work on regarding this?
![screencapture-localhost-3001-2023-10-26-09_46_21](https://github.com/danielschuster-muc/potter-db/assets/68170283/d1a96b87-2c7d-466f-8e6a-8eba9f958560)

**Comment by danielschuster-muc** [comment]
> Hey @danielschuster-muc , I just checked, and looks like the scroll-up button already exists on the newer version. Could you please confirm with me if there is anything else I can work on regarding this?
> ![screencapture-localhost-3001-2023-10-26-09_46_21](https://user-images.githubusercontent.com/68170283/278363977-d1a96b87-2c7d-466f-8e6a-8eba9f958560.png)

No, no, potterdb.com is actually the old website, checkout: https://beta.potterdb.com/

**Comment by kristenking** [comment]
Thank you for a quick response @danielschuster-muc ! I am new to this project and might need some guidance. I followed general guidelines to contribute to a front end and checked localhost: 3001. That gave me old version of the website. Where can I find the codebase for a new website?

**Comment by Shantanu-Tiwari** [comment]
Hey, I would like to work on this issue if its not being worked upon.

**Comment by danielschuster-muc** [comment]
> Thank you for a quick response @danielschuster-muc ! I am new to this project and might need some guidance. I followed general guidelines to contribute to a front end and checked localhost: 3001. That gave me old version of the website. Where can I find the codebase for a new website?

You need to checkout to the `new-website` branch, e.g. with `git checkout new-website`.

**Comment by danielschuster-muc** [comment]
> Hey, I would like to work on this issue if its not being worked upon.

Sorry, it’s already been working on.

**Comment by kristenking** [comment]
> > Thank you for a quick response @danielschuster-muc ! I am new to this project and might need some guidance. I followed general guidelines to contribute to a front end and checked localhost: 3001. That gave me old version of the website. Where can I find the codebase for a new website?
> 
> You need to checkout to the `new-website` branch, e.g. with `git checkout new-website`.

Cool, have it now, thanks so much @danielschuster-muc !
