### ISSUE TITLE
[DOCS/BUG]: update readme

### ISSUE THREAD

**Issue by bugITwhisperer** [danielschuster-muc/potter-db#809]
### Project

Documentation (docs.potterdb.com)

### Describe the ticket you want to create

Jumping to "Security" section in README.md does not work
Jumping to "Authors & Contributors" section in README.md does not work

### Acceptance Criteria
- [ ] update security link in readme.md
- [ ] update authors link in readme.md

**Comment by danielschuster-muc** [comment]
Hi, thank you for you issue. Indeed, the links seem to be broken. Feel free to make a PR for that.
